# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiCnvCGM.ui'
#
# Created: Mon Jan 27 13:30:15 2014
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(827, 835)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 811, 761))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.txtCGMname = QtGui.QLineEdit(self.layoutWidget)
        self.txtCGMname.setObjectName("txtCGMname")
        self.horizontalLayout.addWidget(self.txtCGMname)
        self.pbGetCGM = QtGui.QPushButton(self.layoutWidget)
        self.pbGetCGM.setObjectName("pbGetCGM")
        self.horizontalLayout.addWidget(self.pbGetCGM)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.txtSVGname = QtGui.QLineEdit(self.layoutWidget)
        self.txtSVGname.setObjectName("txtSVGname")
        self.horizontalLayout_2.addWidget(self.txtSVGname)
        self.pbGetSVG = QtGui.QPushButton(self.layoutWidget)
        self.pbGetSVG.setObjectName("pbGetSVG")
        self.horizontalLayout_2.addWidget(self.pbGetSVG)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.pbConvert = QtGui.QPushButton(self.layoutWidget)
        self.pbConvert.setObjectName("pbConvert")
        self.horizontalLayout_3.addWidget(self.pbConvert)
        self.pbShowSVG = QtGui.QPushButton(self.layoutWidget)
        self.pbShowSVG.setObjectName("pbShowSVG")
        self.horizontalLayout_3.addWidget(self.pbShowSVG)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.txtKeywords = QtGui.QTextEdit(self.layoutWidget)
        self.txtKeywords.setObjectName("txtKeywords")
        self.gridLayout.addWidget(self.txtKeywords, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pbSaveKeywords = QtGui.QPushButton(self.layoutWidget)
        self.pbSaveKeywords.setObjectName("pbSaveKeywords")
        self.horizontalLayout_4.addWidget(self.pbSaveKeywords)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pbQuit = QtGui.QPushButton(self.layoutWidget)
        self.pbQuit.setObjectName("pbQuit")
        self.horizontalLayout_4.addWidget(self.pbQuit)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.gridLayout.setRowMinimumHeight(3, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "CGM File:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbGetCGM.setText(QtGui.QApplication.translate("MainWindow", "Get", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "SVG  File", None, QtGui.QApplication.UnicodeUTF8))
        self.pbGetSVG.setText(QtGui.QApplication.translate("MainWindow", "SVG", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MainWindow", "CGM created on Windows ", None, QtGui.QApplication.UnicodeUTF8))
        self.pbConvert.setText(QtGui.QApplication.translate("MainWindow", "CONVERT", None, QtGui.QApplication.UnicodeUTF8))
        self.pbShowSVG.setText(QtGui.QApplication.translate("MainWindow", "Show SVG", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveKeywords.setText(QtGui.QApplication.translate("MainWindow", "Save Keywords", None, QtGui.QApplication.UnicodeUTF8))
        self.pbQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))

